/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.DangNhapDAO;
import DAO.DiemDAO;
import DAO.LopDAO;
import DAO.MonHocDAO;
import DAO.SinhVienDAO;
import static UI.QuanLyGUI.phanQuyen;
import core.SinhVien;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pro
 */
public class DiemGUI extends javax.swing.JDialog {

    /**
     * Creates new form DiemGUI
     */
    private LopDAO lopDAO;
    private MonHocDAO monHocDAO;
    private DiemDAO diemDAO;
    private SinhVienDAO sinhvienDAO;
    private DangNhapDAO dangnhapDAO;
    private String tenLop = "";
    public static ArrayList<SinhVien> listsv = null;

    public DiemGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();
            setColor();
            lopDAO = new LopDAO();
            monHocDAO = new MonHocDAO();
            diemDAO = new DiemDAO();
            sinhvienDAO = new SinhVienDAO();
            dangnhapDAO = new DangNhapDAO();
            dangnhapDAO.loadCombobox(jComboBoxKhoa);
            jComboBoxKhoa.setSelectedItem(DangNhapGUI.siteNow);
            jComboBoxKhoa.removeItem("Phòng Kế Toán");

            monHocDAO.loadComboboxTenMon(jComboBoxTenMon);
            jComboBoxLan.addItem("1");
            jComboBoxLan.addItem("2");
            this.txtMaMon.setEditable(false);
            this.txtTenLop.setEditable(false);
            jComboBoxTenMon.setSelectedItem(0);
            jComboBoxLan.setSelectedItem(0);

            load();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    private DiemGUI() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setColor() {
        this.getContentPane().setBackground(Color.orange);
        this.jButtonBatDau.setBackground(Color.GREEN);
        this.jButton3.setBackground(Color.red);
    }

    public void load() {
        try {
            this.jComboBoxMaLop.removeAllItems();
            lopDAO.loadComboboxLop(jComboBoxMaLop);
            jComboBoxMaLop.setSelectedItem(0);
            tenLop = lopDAO.tenLop(jComboBoxMaLop);
            this.txtTenLop.setText(tenLop);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    public void checkPermission() {

        if (QuanLyGUI.phanQuyen.equals("PGV")) {

        } else if (phanQuyen.equals("KHOA")) {
            this.jComboBoxKhoa.setEnabled(false);

        } else if (phanQuyen.equals("USER")) {
            jComboBoxKhoa.setEnabled(false);
        } else if (phanQuyen.equals("PKeToan")) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxMaLop = new javax.swing.JComboBox<>();
        txtTenLop = new javax.swing.JTextField();
        jComboBoxLan = new javax.swing.JComboBox<>();
        txtMaMon = new javax.swing.JTextField();
        jComboBoxTenMon = new javax.swing.JComboBox<>();
        jButtonBatDau = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxKhoa = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("CẬP NHẬT ĐIỂM MÔN HỌC");

        jLabel3.setText("Mã Lớp:");

        jLabel4.setText("Tên Lớp:");

        jLabel5.setText("Tên Môn:");

        jLabel6.setText("Mã Môn:");

        jLabel8.setText("Lần:");

        jComboBoxMaLop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMaLopItemStateChanged(evt);
            }
        });

        jComboBoxLan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLanActionPerformed(evt);
            }
        });

        jComboBoxTenMon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTenMonItemStateChanged(evt);
            }
        });

        jButtonBatDau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Start-icon.png"))); // NOI18N
        jButtonBatDau.setText("Bắt Đầu");
        jButtonBatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatDauActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-exit-icon.png"))); // NOI18N
        jButton3.setText("Thoát");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Khoa:");

        jComboBoxKhoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxKhoaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(198, 198, 198))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenLop)
                            .addComponent(jComboBoxMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTenMon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jButtonBatDau)
                                        .addGap(64, 64, 64)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(26, 26, 26)
                                .addComponent(jComboBoxLan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addComponent(jComboBoxKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxLan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBatDau)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMaLopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMaLopItemStateChanged

        try {
            // TODO add your handling code here:
            tenLop = lopDAO.tenLop(jComboBoxMaLop);
            this.txtTenLop.setText(tenLop);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

    }//GEN-LAST:event_jComboBoxMaLopItemStateChanged

    private void jComboBoxTenMonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTenMonItemStateChanged
        try {
            // TODO add your handling code here:
            this.txtMaMon.setText(monHocDAO.maMon(jComboBoxTenMon));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_jComboBoxTenMonItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonBatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatDauActionPerformed

        try {
            // TODO add your handling code here:
            // show dialog
            listsv = sinhvienDAO.timSinhVienTheoLop((String) jComboBoxMaLop.getSelectedItem());
            removeStudentExits();
            if (jComboBoxLan.getSelectedItem().equals("2") && checkExitsStudent() == false) {
                JOptionPane.showMessageDialog(rootPane, "Lớp có sinh viên chưa nhập điểm của môn học này lần 1");
                return;
            } else if (listsv.size() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Lớp này không có sinh viên nào");
                return;
            }
            DiemUPDATE diemUPDATE = new DiemUPDATE(this, true, (String) jComboBoxMaLop.getSelectedItem(), txtMaMon.getText(), Integer.parseInt((String) jComboBoxLan.getSelectedItem()), listsv);
            diemUPDATE.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }


    }//GEN-LAST:event_jButtonBatDauActionPerformed

    private void jComboBoxKhoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxKhoaItemStateChanged
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Program.changeSite = "Change";
            Program.serverName = dangnhapDAO.getServerName(jComboBoxKhoa);

            load();
            checkPermission();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_jComboBoxKhoaItemStateChanged

    private void jComboBoxLanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiemGUI dialog = new DiemGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void removeStudentExits() {
        for (int i = 0; i < listsv.size(); i++) {
            if (listsv.get(i).isNGHIHOC()) {
                listsv.remove(i);
            }
        }
    }

    public boolean checkExitsStudent() {
        try {
            String check = "";
            for (int i = 0; i < listsv.size(); i++) {
                check = diemDAO.timDiemPROC(listsv.get(i).getMASV(), txtMaMon.getText(), 1);
                if (check == null) {
                    return false;
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonBatDau;
    private javax.swing.JComboBox<String> jComboBoxKhoa;
    private javax.swing.JComboBox<String> jComboBoxLan;
    private javax.swing.JComboBox<String> jComboBoxMaLop;
    private javax.swing.JComboBox<String> jComboBoxTenMon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtMaMon;
    private javax.swing.JTextField txtTenLop;
    // End of variables declaration//GEN-END:variables
}
