/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.DiemDAO;
import DAO.SinhVienDAO;
import static UI.QuanLyGUI.phanQuyen;
import core.Diem;
import core.SinhVien;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pro
 */
public class DiemUPDATE extends javax.swing.JDialog {

    /**
     * Creates new form DiemUPDATE2
     */
    private SinhVienDAO sinhvienDAO;
    private DiemDAO diemDAO;

    public static String maLop = "";
    public static String maMH = "";
    public static int lan;
    private ArrayList<SinhVien> list = null;
    private ArrayList<Diem> listDiem = null;
    private Object[][] data = {};
    float checkDiem;

    public DiemUPDATE(java.awt.Dialog parent, boolean modal, String maLop, String maMH, int lan, ArrayList<SinhVien> list) {
        super(parent, modal);
        sinhvienDAO = new SinhVienDAO();
        diemDAO = new DiemDAO();
        listDiem = new ArrayList<Diem>();
        this.maLop = maLop;
        this.maMH = maMH;
        this.lan = lan;
        this.list = list;
        initComponents();
        setColor();
        danhSachSinhVien();
        this.jTextFieldMaSV.setEditable(false);
        this.jTextFieldMaMH.setEditable(false);
        this.jTextFieldLan.setEditable(false);
        this.jTextFieldMaMH.setText(this.maMH);
        this.jTextFieldLan.setText(Integer.toString(lan));
        checkPermission();

    }

    public void setColor() {
        this.getContentPane().setBackground(Color.orange);
        this.jButtonGhiDiem.setBackground(Color.GREEN);
        this.jButtonThoat.setBackground(Color.red);
    }

    public void checkPermission() {

        if (QuanLyGUI.phanQuyen.equals("PGV")) {

        } else if (phanQuyen.equals("KHOA")) {
            if (Program.changeSite.equals("Change") && !Program.serverName.equals(DangNhapGUI.serverNow)) {
                this.jButtonGhiDiem.setEnabled(false);
            }
        } else if (phanQuyen.equals("USER")) {

        } else if (phanQuyen.equals("PKeToan")) {

        }
    }

    private DiemUPDATE() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonGhiDiem = new javax.swing.JButton();
        jButtonThoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMaSV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMaMH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldLan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonGhiDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Save-icon.png"))); // NOI18N
        jButtonGhiDiem.setText("Ghi Điểm");
        jButtonGhiDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGhiDiemActionPerformed(evt);
            }
        });

        jButtonThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-exit-icon.png"))); // NOI18N
        jButtonThoat.setText("Thoát");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("NHẬP ĐIỂM");

        jLabel2.setText("Mã SV:");

        jLabel3.setText("Mã MH:");

        jLabel4.setText("Lần:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGhiDiem)
                .addGap(70, 70, 70)
                .addComponent(jButtonThoat)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMaSV, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jTextFieldMaMH)
                    .addComponent(jTextFieldLan))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonThoat)
                            .addComponent(jButtonGhiDiem))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            // TODO add your handling code here:
            inMaSV();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonThoatActionPerformed

    private void jButtonGhiDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGhiDiemActionPerformed
        // TODO add your handling code here:
        
        jTable1.requestFocus();
        jTable1.editCellAt(0,0);

        saveDiem();
    }//GEN-LAST:event_jButtonGhiDiemActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_jTable1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiemUPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiemUPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiemUPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiemUPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiemUPDATE().setVisible(true);
            }
        });
    }

    public void danhSachSinhVien() {
        try {
            String[] header = {"Mã SV", "HỌ & TÊN", "ĐIỂM"};
            data = new Object[list.size()][3];
            for (int i = 0; i < list.size(); i++) {
                //System.out.println(list.size()+"_"+list.get(i).getMASV());
                data[i][0] = list.get(i).getMASV();
                data[i][1] = list.get(i).getHO() + " " + list.get(i).getTEN();
                data[i][2] = diemDAO.timDiemPROC(list.get(i).getMASV(), DiemUPDATE.maMH, DiemUPDATE.lan);
            }
            DefaultTableModel model = new DefaultTableModel(data, header);
            jTable1.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }

    }

    public void inMaSV() throws SQLException {
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(rootPane, "Bạn phải chọn sinh viên");
            return;
        }
        String tempSV = (String) jTable1.getValueAt(row, 0);
        this.jTextFieldMaSV.setText(tempSV);
    }

    protected void saveDiem() {

        try {
            String status = "";
            // get the student info from gui
            String[] MASV = new String[list.size()];
            float[] Diem = new float[list.size()];
            String isDiem;
            String MAMH = jTextFieldMaMH.getText();
            int Lan = Integer.parseInt(jTextFieldLan.getText());
            for (int i = 0; i < list.size(); i++) {
                if (jTable1.getValueAt(i, 2).toString().trim().equals("")) {
                    JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập điểm sinh viên có mã " + data[i][0] + "");
                    return;
                } else {
                    MASV[i] = (String) data[i][0];
                    Diem[i] = Float.parseFloat((String) jTable1.getValueAt(i, 2));
                    isDiem = diemDAO.timDiemPROC(MASV[i], this.maMH, this.lan);
                    Diem diemOBJ = null;
                    // save to the database
                    if (isDiem != null) {
                        diemOBJ = new Diem(MASV[i], MAMH, Lan, Diem[i]);
                        diemDAO.capNhatDiemPROC(diemOBJ);
                        status = "CapNhat";
                    } else {
                        diemOBJ = new Diem(MASV[i], MAMH, Lan, Diem[i]);
                        diemDAO.themDiemPROC(diemOBJ);
                        status = "Them";
                    }
                }
            }
            if (status.equals("CapNhat")) {
                JOptionPane.showMessageDialog(this,
                        "Cập nhật điểm thành công.",
                        "",
                        JOptionPane.INFORMATION_MESSAGE);

            } else if (status.equals("Them")) {
                JOptionPane.showMessageDialog(this,
                        "Thêm điểm thành công",
                        "",
                        JOptionPane.INFORMATION_MESSAGE);

            }
            danhSachSinhVien();

        } catch (Exception exc) {
            JOptionPane.showMessageDialog(
                    this,
                    "Lỗi lưu điểm: "
                    + exc.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
//         try {
//             danhSachSinhVien1();
//         } catch (SQLException ex) {
//             JOptionPane.showMessageDialog(rootPane, ex.getMessage());
//         }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGhiDiem;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldLan;
    private javax.swing.JTextField jTextFieldMaMH;
    private javax.swing.JTextField jTextFieldMaSV;
    // End of variables declaration//GEN-END:variables
}
