/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.HocPhiDAO;
import DAO.SinhVienDAO;
import core.HocPhi;
import core.SinhVien;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pro
 */
public final class HocPhiGUI extends javax.swing.JDialog {

    /**
     * Creates new form HocPhiGUI
     */
    private final SinhVienDAO sinhvienDAO;
    private final HocPhiDAO hocphiDAO;
    public String status = "";
    private final boolean checkHP;
    private ArrayList<HocPhi> list;
    private Object[][] data = {};
    private String checkMASV = "";
    private SinhVien sv;
    private final String[] header = {"NIÊN KHÓA", "HỌC KỲ", "HỌC PHÍ", "SỐ TIỀN ĐÃ ĐÓNG"};

    public HocPhiGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setColor();
        sinhvienDAO = new SinhVienDAO();
        hocphiDAO = new HocPhiDAO();
        checkHP = true;
        list = null;
        this.jTextFieldHo.setEditable(false);
        this.jTextFieldTen.setEditable(false);
        this.jTextFieldMaLop.setEditable(false);
        initTable();
    }

    public void setColor() {
        this.getContentPane().setBackground(Color.orange);
        this.jButtonGhi.setBackground(Color.GREEN);
        this.jButtonThoat.setBackground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMASV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldHo = new javax.swing.JTextField();
        jTextFieldTen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHocPhi = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldMaLop = new javax.swing.JTextField();
        jButtonGhi = new javax.swing.JButton();
        jButtonThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("            ĐÓNG HỌC PHÍ");

        jTextFieldMASV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldMASVMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextFieldMASVMouseReleased(evt);
            }
        });
        jTextFieldMASV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldMASVKeyReleased(evt);
            }
        });

        jLabel3.setText("Mã SV:");

        jLabel4.setText("Họ: ");

        jLabel5.setText("Tên:");

        jTableHocPhi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableHocPhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHocPhiMouseClicked(evt);
            }
        });
        jTableHocPhi.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableHocPhiPropertyChange(evt);
            }
        });
        jTableHocPhi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableHocPhiKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableHocPhiKeyReleased(evt);
            }
        });
        jTableHocPhi.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jTableHocPhiVetoableChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTableHocPhi);

        jLabel6.setText("Mã Lớp:");

        jButtonGhi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Save-icon.png"))); // NOI18N
        jButtonGhi.setText("Ghi");
        jButtonGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGhiActionPerformed(evt);
            }
        });

        jButtonThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-exit-icon.png"))); // NOI18N
        jButtonThoat.setText("Thoát");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMASV)
                            .addComponent(jTextFieldHo)
                            .addComponent(jTextFieldTen)
                            .addComponent(jTextFieldMaLop, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(338, 338, 338))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonGhi, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButtonThoat)
                        .addGap(207, 207, 207))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMASV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGhi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonThoatActionPerformed

    private void jTextFieldMASVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldMASVMousePressed

    }//GEN-LAST:event_jTextFieldMASVMousePressed

    private void jTextFieldMASVMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldMASVMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldMASVMouseReleased

    private void jTextFieldMASVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMASVKeyReleased
        // TODO add your handling code here:
        danhSachHocPhiSinhVien();
    }//GEN-LAST:event_jTextFieldMASVKeyReleased

    private void jTableHocPhiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHocPhiMouseClicked
        // TODO add your handling code here:
        //setData();
    }//GEN-LAST:event_jTableHocPhiMouseClicked

    private void jButtonGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGhiActionPerformed
        // TODO add your handling code here:
        jTableHocPhi.requestFocus();
        jTableHocPhi.editCellAt(0,0);
        if (jTextFieldMASV.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập mã sinh viên.");
        } else {
            saveHocPhi();
        }

    }//GEN-LAST:event_jButtonGhiActionPerformed

    private void jTableHocPhiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableHocPhiKeyReleased
        // TODO add your handling code here:
        // setData();
    }//GEN-LAST:event_jTableHocPhiKeyReleased

    private void jTableHocPhiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableHocPhiKeyPressed
        // TODO add your handling code here:
        //setData();
    }//GEN-LAST:event_jTableHocPhiKeyPressed

    private void jTableHocPhiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableHocPhiPropertyChange
        // TODO add your handling code here:
        //setData();
    }//GEN-LAST:event_jTableHocPhiPropertyChange

    private void jTableHocPhiVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jTableHocPhiVetoableChange
        // TODO add your handling code here:
        //setData();
    }//GEN-LAST:event_jTableHocPhiVetoableChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HocPhiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HocPhiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HocPhiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HocPhiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HocPhiGUI dialog = new HocPhiGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void initTable() {
        list = null;
        data = new Object[0][0];
        DefaultTableModel model1 = new DefaultTableModel(data, header);
        jTableHocPhi.setModel(model1);
    }

    public void danhSachHocPhiSinhVien() {
        try {
            initTable();
            String maSV = jTextFieldMASV.getText();
            sv = sinhvienDAO.timSinhVienTheoMaSV(maSV);
            if (sv == null) {
                jTextFieldHo.setText("");
                jTextFieldTen.setText("");
                jTextFieldMaLop.setText("");
                return;
            } else {
                if (sv.isNGHIHOC() == true) {
                    JOptionPane.showMessageDialog(rootPane, "Sinh viên này đã nghỉ học");
                    jTextFieldMASV.setText("");
                    return;
                }
                jTextFieldHo.setText(sv.getHO());
                jTextFieldTen.setText(sv.getTEN());
                jTextFieldMaLop.setText(sv.getMALOP());
                checkMASV = hocphiDAO.kiemTraMaSVhocPhi(maSV);

                if (checkMASV == null) {
                    DefaultTableModel model = new DefaultTableModel(data, header);
                    jTableHocPhi.setModel(model);
                } else {
                    list = new ArrayList<HocPhi>();
                    list = hocphiDAO.timHocPhi(maSV);
                    data = new Object[list.size()][4];

                    for (int i = 0; i < list.size(); i++) {
                        // System.out.println(list.size()+"_"+list.get(i).getMASV());
                        data[i][0] = list.get(i).getNIENKHOA();
                        data[i][1] = list.get(i).getHOCKY();
                        data[i][2] = Integer.toString(list.get(i).getHOCPHI());
                        data[i][3] = Integer.toString(list.get(i).getSOTIENDADONG());
                    }

                    DefaultTableModel model = new DefaultTableModel(data, header);
                    jTableHocPhi.setModel(model);

                }

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }

    }

    protected void saveHocPhi() {

        try {
            String MASV = jTextFieldMASV.getText();

            HocPhi tempHocPhi = null;
            String[] NienKhoa = new String[list.size()];
            int[] HOCKY = new int[list.size()];
            int[] HocPhi = new int[list.size()];
            int[] SoTienDaDong = new int[list.size()];

            for (int i = 0; i < list.size(); i++) {
                if (jTableHocPhi.getValueAt(i, 2).equals("") || jTableHocPhi.getValueAt(i, 3).equals("")) {
                    JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập học phí có niên khóa: " + data[i][0] + "  Học kì: " + data[i][1] + "");
                    return;
                } else {

                    NienKhoa[i] = (String) data[i][0];
                    HOCKY[i] = (int) data[i][1];
                    HocPhi[i] = Integer.parseInt((String) jTableHocPhi.getValueAt(i, 2));
                    SoTienDaDong[i] = Integer.parseInt((String) jTableHocPhi.getValueAt(i, 3));
                    tempHocPhi = new HocPhi(MASV, NienKhoa[i], HOCKY[i], HocPhi[i], SoTienDaDong[i]);
                    hocphiDAO.capNhatHocPhiPROC(tempHocPhi);
                    status = "CapNhat";
                }

            }

            // get the student info from gui
            if (status.equals("CapNhat")) {

                // show success message
                JOptionPane.showMessageDialog(this,
                        "Cập nhật học phí thành công.",
                        "",
                        JOptionPane.INFORMATION_MESSAGE);
            }

            // refresh gui list
            danhSachHocPhiSinhVien();

        } catch (Exception exc) {
            System.out.println("" + exc.getMessage());
            JOptionPane.showMessageDialog(
                    this,
                    "Lỗi lưu học phí: "
                    + exc.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGhi;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHocPhi;
    private javax.swing.JTextField jTextFieldHo;
    private javax.swing.JTextField jTextFieldMASV;
    private javax.swing.JTextField jTextFieldMaLop;
    private javax.swing.JTextField jTextFieldTen;
    // End of variables declaration//GEN-END:variables
}
