/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import JasperReport.reportDiem;
import DAO.DangNhapDAO;
import DAO.DiemDAO;
import DAO.LopDAO;
import DAO.MonHocDAO;
import static UI.QuanLyGUI.phanQuyen;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Pro
 */
public class InPhieuDiemThiGUI extends javax.swing.JDialog {

    /**
     * Creates new form InPhieuDiemThiGUI
     */
    private LopDAO lopDAO;
    private MonHocDAO monHocDAO;
    private DiemDAO diemDAO;
    private DangNhapDAO dangnhapDAO;
    public String maMH = "";
    public String maLop = "";
    public static int hocki = 1;

    public InPhieuDiemThiGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();
            setColor();
            lopDAO = new LopDAO();
            monHocDAO = new MonHocDAO();
            diemDAO = new DiemDAO();
            dangnhapDAO = new DangNhapDAO();
            dangnhapDAO.loadCombobox(jComboBoxKhoa);
            jComboBoxKhoa.setSelectedItem(DangNhapGUI.siteNow);
            jComboBoxKhoa.removeItem("Phòng Kế Toán");

            monHocDAO.loadComboboxTenMon(jComboBoxTenMon);
            jComboBoxLan.addItem("1");
            jComboBoxLan.addItem("2");
            jComboBoxTenMon.setSelectedItem(0);
            jComboBoxLan.setSelectedItem(0);

            load();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    public void setColor() {
        this.getContentPane().setBackground(Color.orange);
        this.jButtonManHinh.setBackground(Color.GREEN);
        this.jButtonMayIn.setBackground(Color.magenta);
        this.jButtonThoat.setBackground(Color.red);
    }

    public void load() {
        try {
            this.jComboBoxTenLop.removeAllItems();
            lopDAO.loadComboboxTenLop(jComboBoxTenLop);
            jComboBoxTenLop.setSelectedItem(0);
            maLop = lopDAO.maLop(jComboBoxTenLop);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

    }

    public void checkPermission() {

        if (QuanLyGUI.phanQuyen.equals("PGV")) {

        } else if (phanQuyen.equals("KHOA")) {

        } else if (phanQuyen.equals("USER")) {
            jComboBoxKhoa.setEnabled(false);
        } else if (phanQuyen.equals("PKeToan")) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxKhoa = new javax.swing.JComboBox<>();
        jComboBoxTenLop = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxTenMon = new javax.swing.JComboBox<>();
        jTextFieldHocKi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNgayThi = new javax.swing.JTextField();
        jComboBoxLan = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButtonManHinh = new javax.swing.JButton();
        jButtonMayIn = new javax.swing.JButton();
        jButtonThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tên Lớp:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("PHIẾU ĐIỂM THI");

        jLabel3.setText("Khoa:");

        jComboBoxKhoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxKhoaItemStateChanged(evt);
            }
        });

        jComboBoxTenLop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTenLopItemStateChanged(evt);
            }
        });

        jLabel5.setText("Tên Môn:");

        jComboBoxTenMon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTenMonItemStateChanged(evt);
            }
        });

        jTextFieldHocKi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldHocKiKeyPressed(evt);
            }
        });

        jLabel6.setText("Ngày Thi:");

        jLabel7.setText("Học kì:");

        jTextFieldNgayThi.setText("22-08-1997");
        jTextFieldNgayThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNgayThiActionPerformed(evt);
            }
        });
        jTextFieldNgayThi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNgayThiKeyPressed(evt);
            }
        });

        jComboBoxLan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLanActionPerformed(evt);
            }
        });

        jLabel8.setText("Lần Thi:");

        jButtonManHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/terminal-icon.png"))); // NOI18N
        jButtonManHinh.setText("Màn Hình");
        jButtonManHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManHinhActionPerformed(evt);
            }
        });

        jButtonMayIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/print-scan-icon.png"))); // NOI18N
        jButtonMayIn.setText("Máy In");

        jButtonThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-exit-icon.png"))); // NOI18N
        jButtonThoat.setText("Thoát");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addComponent(jLabel8))
                        .addGap(1, 1, 1)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxLan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldHocKi)
                    .addComponent(jComboBoxKhoa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxTenLop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxTenMon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNgayThi, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonManHinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMayIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonThoat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonManHinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMayIn)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonThoat)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jTextFieldHocKi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNgayThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxLan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxLanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLanActionPerformed

    private void jTextFieldNgayThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNgayThiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNgayThiActionPerformed

    private void jComboBoxKhoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxKhoaItemStateChanged
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Program.changeSite = "Change";
            Program.serverName = dangnhapDAO.getServerName(jComboBoxKhoa);

            load();
            checkPermission();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_jComboBoxKhoaItemStateChanged

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonThoatActionPerformed

    private void jButtonManHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManHinhActionPerformed

        if (jTextFieldNgayThi.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "vui lòng nhập ngày thi");
        } else if (jTextFieldHocKi.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "vui lòng nhập học kì");
        } else {
            hocki = Integer.parseInt(jTextFieldHocKi.getText());
            try {
                // TODO add your handling code here:
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                String NgayThiString = jTextFieldNgayThi.getText();
                int lan = Integer.parseInt((String) jComboBoxLan.getSelectedItem());
                Date NgayThi = (Date) sdf.parse(NgayThiString);
                reportDiem diemReport = new reportDiem((String) jComboBoxTenLop.getSelectedItem(), (String) jComboBoxTenMon.getSelectedItem(), maMH, NgayThi, lan, maLop);
                this.dispose();
            } catch (ParseException | JRException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
        }
    }//GEN-LAST:event_jButtonManHinhActionPerformed

    private void jComboBoxTenMonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTenMonItemStateChanged
        try {
            // TODO add your handling code here:
            maMH = monHocDAO.maMon(jComboBoxTenMon);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_jComboBoxTenMonItemStateChanged

    private void jComboBoxTenLopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTenLopItemStateChanged
        try {
            // TODO add your handling code here:
            maLop = lopDAO.maLop(jComboBoxTenLop);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_jComboBoxTenLopItemStateChanged

    private void jTextFieldHocKiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldHocKiKeyPressed
        // TODO add your handling code here:
        jTextFieldHocKi.setEditable(false);
        if ((evt.getKeyChar() >= 48 && evt.getKeyChar() <= 57) || evt.getKeyChar() == 8) {
            jTextFieldHocKi.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldHocKiKeyPressed

    private void jTextFieldNgayThiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNgayThiKeyPressed
        // TODO add your handling code here:
        jTextFieldNgayThi.setEditable(false);
        if ((evt.getKeyChar() >= 48 && evt.getKeyChar() <= 57) || evt.getKeyChar() == 45 || evt.getKeyChar() == 8) {
            jTextFieldNgayThi.setEditable(true);
        }
    }//GEN-LAST:event_jTextFieldNgayThiKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InPhieuDiemThiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InPhieuDiemThiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InPhieuDiemThiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InPhieuDiemThiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InPhieuDiemThiGUI dialog = new InPhieuDiemThiGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonManHinh;
    private javax.swing.JButton jButtonMayIn;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JComboBox<String> jComboBoxKhoa;
    private javax.swing.JComboBox<String> jComboBoxLan;
    private javax.swing.JComboBox<String> jComboBoxTenLop;
    private javax.swing.JComboBox<String> jComboBoxTenMon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldHocKi;
    private javax.swing.JTextField jTextFieldNgayThi;
    // End of variables declaration//GEN-END:variables
}
