/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.DangNhapDAO;
import DAO.LopDAO;
import static UI.QuanLyGUI.phanQuyen;
import core.Lop;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author Pro
 */
public class LopGUI extends javax.swing.JDialog {

    /**
     * Creates new form LopGUI
     */
    private LopDAO lopDAO;
    private DangNhapDAO dangnhapDAO;
    public static String statusLop = "";
    public static Stack<Lop> stack = null;
    public static Stack<String> strings = null;

    public LopGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();
            setColor();
            dangnhapDAO = new DangNhapDAO();
            stack = new Stack<Lop>();
            strings = new Stack<String>();
            dangnhapDAO.loadCombobox(jComboBoxKhoa);
            jComboBoxKhoa.setSelectedItem(DangNhapGUI.siteNow);
            jComboBoxKhoa.removeItem("Phòng Kế Toán");
            danhSachLop();
            checkPermission();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    public void setColor() {
        this.getContentPane().setBackground(Color.orange);
        this.btnThem.setBackground(Color.GREEN);
        this.btnGhi.setBackground(Color.magenta);
        this.btnXoa.setBackground(Color.red);
        this.btnPhucHoi.setBackground(Color.yellow);
        this.btnThoat.setBackground(Color.red);
    }

    public void checkPermission() {

        if (QuanLyGUI.phanQuyen.equals("PGV")) {

        } else if (phanQuyen.equals("KHOA")) {
            this.jComboBoxKhoa.setEnabled(false);
        } else if (phanQuyen.equals("USER")) {
            this.jComboBoxKhoa.setEnabled(false);
        } else if (phanQuyen.equals("PKeToan")) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLop = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnGhi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnPhucHoi = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxKhoa = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableLop);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("                               DANH SÁCH LỚP");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Add-icon.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnGhi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit-validated-icon.png"))); // NOI18N
        btnGhi.setText("Sửa");
        btnGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Close-icon.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnPhucHoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/redo-icon.png"))); // NOI18N
        btnPhucHoi.setText("Phục Hồi");
        btnPhucHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhucHoiActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-exit-icon.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel2.setText("Khoa:");

        jComboBoxKhoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxKhoaItemStateChanged(evt);
            }
        });
        jComboBoxKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxKhoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnThem)
                .addGap(29, 29, 29)
                .addComponent(btnGhi)
                .addGap(28, 28, 28)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnPhucHoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(56, 56, 56)
                        .addComponent(jComboBoxKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem)
                        .addComponent(btnGhi)
                        .addComponent(btnPhucHoi)
                        .addComponent(btnThoat)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            // TODO add your handling code here:
            statusLop = "Them";
            LopUPDATE add = new LopUPDATE(this, lopDAO);
            add.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiActionPerformed
        // TODO add your handling code here:
        statusLop = "CapNhat";
        try {
            capNhatLop();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnGhiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        xoaLop();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnPhucHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhucHoiActionPerformed
        // TODO add your handling code here:

        if (strings.isEmpty() && stack.isEmpty()) {
            return;
        } else {
            String check = strings.pop();
            if (check.equals("Them")) {
                try {
                    int response = JOptionPane.showConfirmDialog(
                            this, "Bạn có muốn xóa lớp vừa thêm không?", "Confirm",
                            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (response != JOptionPane.YES_OPTION) {
                        return;
                    }
                    // get the current 
                    Lop tempLop = stack.pop();
                    // delete the student
                    lopDAO.xoaLopPROC(tempLop.getMALOP());
                    // refrprocessesh GUI
                    danhSachLop();
                } catch (SQLException ex) {
                    JOptionPane.showConfirmDialog(rootPane, ex.getMessage());
                }
            } else if (check.equals("CapNhat")) {
                try {
                    Lop tempLop = stack.pop();
                    // delete the student
                    lopDAO.capNhatLopPROC(tempLop);
                    // refrprocessesh GUI
                    danhSachLop();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane, ex);
                }
            } else if (check.equals("Xoa")) {
                try {
                    Lop tempLop = stack.pop();
                    // delete the student
                    lopDAO.themLopPROC(tempLop);
                    //refrprocessesh GUI
                    danhSachLop();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane, ex);
                }
            }

        }
    }//GEN-LAST:event_btnPhucHoiActionPerformed

    private void jComboBoxKhoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxKhoaItemStateChanged
        try {
            // TODO add your handling code here:
            Program.changeSite = "Change";
            Program.serverName = dangnhapDAO.getServerName(jComboBoxKhoa);
            danhSachLop();
            checkPermission();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_jComboBoxKhoaItemStateChanged

    private void jComboBoxKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxKhoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LopGUI dialog = new LopGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void danhSachLop() {
        try {
            lopDAO = new LopDAO();
            ArrayList<Lop> dsLop = null;
            dsLop = lopDAO.findAll();
            LopTableModel model = new LopTableModel(dsLop);
            jTableLop.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

    }

    public void capNhatLop() throws SQLException {

        // get the selected item
        int row = jTableLop.getSelectedRow();

        // make sure a row is selected
        if (row < 0) {
            JOptionPane.showMessageDialog(rootPane, "Bạn phải chọn lớp");
            return;
        }

        // get the current student
        Lop tempLop = (Lop) jTableLop.getValueAt(row, LopTableModel.OBJECT_COL);

        // create dialog
        LopUPDATE dialog = new LopUPDATE(this, lopDAO, tempLop, true);
        // show dialog
        dialog.setVisible(true);
    }

    public void xoaLop() {

        try {
            // get the selected row
            int row = jTableLop.getSelectedRow();

            // make sure a row is selected
            if (row < 0) {
                JOptionPane.showMessageDialog(this,
                        "Bạn phải chọn Lớp", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // prompt the user
            int response = JOptionPane.showConfirmDialog(
                    this, "Bạn có muốn xóa lớp này không?", "Confirm",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (response != JOptionPane.YES_OPTION) {
                return;
            }

            // get the current student
            Lop tempLop = (Lop) jTableLop.getValueAt(row, LopTableModel.OBJECT_COL);
            // delete the student
            lopDAO.xoaLopPROC(tempLop.getMALOP());
            strings.push("Xoa");
            stack.push(tempLop);
            // refrprocessesh GUI
            danhSachLop();

            // show success message
            JOptionPane.showMessageDialog(this,
                    "Xóa lớp thành công.", "Deleted",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception exc) {
            JOptionPane.showMessageDialog(this,
                    "Lỗi xóa lớp: " + exc.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnPhucHoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> jComboBoxKhoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLop;
    // End of variables declaration//GEN-END:variables
}
