/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.MonHocDAO;
import core.MonHoc;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Pro
 */
public class MonHocUPDATE extends javax.swing.JDialog {

    /**
     * Creates new form MonHocUPDATE
     */
    private MonHocDAO monHocDAO;
    private MonHocGUI monHocGUI;

    private MonHoc previousMH = null;
    private boolean updateMode = false;
    MonHoc MHStack = new MonHoc();

    public MonHocUPDATE(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setColor();
        if (MonHocGUI.statusMH.equals("Them")) {
            this.jLabelTieuDe.setText("THÊM MÔN HỌC");

        } else if (MonHocGUI.statusMH.equals("CapNhat")) {
            this.jLabelTieuDe.setText("CẬP NHẬT MÔN HỌC");
            this.txtMaMH.setEditable(false);

        }

    }

    public MonHocUPDATE(MonHocGUI monHocGUI, MonHocDAO monHocDAO) throws SQLException {
        this(monHocGUI, monHocDAO, null, false);
    }

    public MonHocUPDATE(MonHocGUI monHocGUI, MonHocDAO monHocDAO, MonHoc thePreviousMH, boolean theUpdateMode) throws SQLException {
        this(new javax.swing.JFrame(), true);
        this.monHocGUI = monHocGUI;
        this.monHocDAO = monHocDAO;
        this.previousMH = thePreviousMH;
        this.updateMode = theUpdateMode;
        if (updateMode) {

            populateGUI(previousMH);
        }
    }

    private void populateGUI(MonHoc monHoc) {
        txtMaMH.setText(monHoc.getMAMH());
        txtTenMH.setText(monHoc.getTENMH());
        MHStack = monHoc;
    }

    public void setColor() {
        this.getContentPane().setBackground(Color.orange);
        this.btnLuu.setBackground(Color.GREEN);

        this.btnThoat.setBackground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTieuDe = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtMaMH = new javax.swing.JTextField();
        txtTenMH = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTieuDe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel2.setText("Mã MH:");

        jLabel3.setText("Tên MH:");

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Save-icon.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-exit-icon.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        txtMaMH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaMHKeyPressed(evt);
            }
        });

        txtTenMH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenMHKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnThoat))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenMH, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabelTieuDe)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTieuDe)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnThoat))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if (txtMaMH.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "vui lòng nhập mã môn học");
        } else if (txtTenMH.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "vui lòng nhập tên môn học");
        } else {
            saveMH();
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void txtMaMHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaMHKeyPressed
        // TODO add your handling code here:
        txtMaMH.setEditable(false);
        if ((evt.getKeyChar() >= 48 && evt.getKeyChar() <= 57) || (evt.getKeyChar() >= 65 && evt.getKeyChar() <= 122) || evt.getKeyChar() == 8) {
            txtMaMH.setEditable(true);
        }
    }//GEN-LAST:event_txtMaMHKeyPressed

    private void txtTenMHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenMHKeyPressed
        // TODO add your handling code here:  txtMaMH.setEditable(false);

    }//GEN-LAST:event_txtTenMHKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonHocUPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonHocUPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonHocUPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonHocUPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MonHocUPDATE dialog = new MonHocUPDATE(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    protected void saveMH() {

        // get the student info from gui
        String MAMH = txtMaMH.getText();
        String TENMH = txtTenMH.getText();

        MonHoc tempMH = null;

        if (!updateMode) {
            tempMH = new MonHoc(MAMH, TENMH);
        } else {
            tempMH = new MonHoc(previousMH.getMAMH(), TENMH);
        }
        try {
            // save to the database
            if (updateMode) {
                monHocDAO.capNhatMonPROC(tempMH);
                monHocGUI.stringMH.push("CapNhat");
                monHocGUI.stackMH.push(MHStack);
            } else {
                monHocDAO.themMonPROC(tempMH);
                monHocGUI.stringMH.push("Them");
                monHocGUI.stackMH.push(tempMH);
            }
            // close dialog
            setVisible(false);
            dispose();
            // refresh gui list
            monHocGUI.danhSachMonHoc();

            // show success message
            if (!updateMode) {
                JOptionPane.showMessageDialog(monHocGUI,
                        "Thêm môn học thành công",
                        "",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(monHocGUI,
                        "Cập nhật môn học thành công.",
                        "",
                        JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(
                    monHocGUI,
                    "Lỗi lưu môn học: "
                    + exc.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTieuDe;
    private javax.swing.JTextField txtMaMH;
    private javax.swing.JTextField txtTenMH;
    // End of variables declaration//GEN-END:variables
}
