/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.DangNhapDAO;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pro
 */
public class QuanLyGUI extends javax.swing.JFrame {

    /**
     * Creates new form QuanLy
     */
    public static String phanQuyen = "";
    private DangNhapDAO dangNhapDAO;

    public QuanLyGUI() throws SQLException {

        dangNhapDAO = new DangNhapDAO();
        initComponents();
        setColor();
        checkPermission();

    }

    public void setColor() {
        this.getContentPane().setBackground(Color.orange);
        this.jButtonDT.setBackground(Color.YELLOW);
        this.jButtonBDMH.setBackground(Color.YELLOW);
        this.jButtonDSHP.setBackground(Color.YELLOW);
        this.jButtonDSSV.setBackground(Color.YELLOW);
        this.jButtonHocPhi.setBackground(Color.YELLOW);
        this.jButtonLop.setBackground(Color.YELLOW);
        this.jButtonMonHoc.setBackground(Color.YELLOW);
        this.jButtonNhapDiem.setBackground(Color.YELLOW);
        this.jButtonSinhVien.setBackground(Color.YELLOW);
        this.jButtonTaoTaiKhoan.setBackground(Color.YELLOW);
        this.jButtonThoat.setBackground(Color.YELLOW);
        this.jButtonBDTK.setBackground(Color.YELLOW);
        this.jButtonPDSV.setBackground(Color.YELLOW);

    }

    public void checkPermission() throws SQLException {
        phanQuyen = dangNhapDAO.getPermission(Program.userName);
        if (phanQuyen.equals("PGV")) {

            this.jButtonHocPhi.setEnabled(false);
            this.jButtonDSHP.setEnabled(false);
        } else if (phanQuyen.equals("KHOA")) {
            this.jButtonHocPhi.setEnabled(false);
            this.jButtonTaoTaiKhoan.setEnabled(false);
            this.jButtonDSHP.setEnabled(false);
        } else if (phanQuyen.equals("USER")) {
            this.jButtonHocPhi.setEnabled(false);
            this.jButtonTaoTaiKhoan.setEnabled(false);
            this.jButtonDSHP.setEnabled(false);
        } else if (phanQuyen.equals("PKeToan")) {
            this.jButtonLop.setEnabled(false);
            this.jButtonSinhVien.setEnabled(false);
            this.jButtonNhapDiem.setEnabled(false);
            this.jButtonMonHoc.setEnabled(false);
            this.jButtonPDSV.setEnabled(false);
            this.jButtonDSSV.setEnabled(false);
            this.jButtonBDMH.setEnabled(false);
            this.jButtonDT.setEnabled(false);
            this.jButtonBDTK.setEnabled(false);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLop = new javax.swing.JButton();
        jButtonSinhVien = new javax.swing.JButton();
        jButtonMonHoc = new javax.swing.JButton();
        jButtonNhapDiem = new javax.swing.JButton();
        jButtonHocPhi = new javax.swing.JButton();
        jButtonThoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonTaoTaiKhoan = new javax.swing.JButton();
        jButtonDSSV = new javax.swing.JButton();
        jButtonDT = new javax.swing.JButton();
        jButtonBDMH = new javax.swing.JButton();
        jButtonDSHP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonBDTK = new javax.swing.JButton();
        jButtonPDSV = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Science-Classroom-icon.png"))); // NOI18N
        jButtonLop.setText("LỚP");
        jButtonLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLopActionPerformed(evt);
            }
        });

        jButtonSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Student-3-icon.png"))); // NOI18N
        jButtonSinhVien.setText("SINH VIÊN");
        jButtonSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinhVienActionPerformed(evt);
            }
        });

        jButtonMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Book-icon.png"))); // NOI18N
        jButtonMonHoc.setText("MÔN HỌC");
        jButtonMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMonHocActionPerformed(evt);
            }
        });

        jButtonNhapDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/write-document-icon.png"))); // NOI18N
        jButtonNhapDiem.setText("NHẬP ĐIỂM");
        jButtonNhapDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNhapDiemActionPerformed(evt);
            }
        });

        jButtonHocPhi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Pay-Per-Click-icon.png"))); // NOI18N
        jButtonHocPhi.setText("ĐÓNG HỌC PHÍ");
        jButtonHocPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHocPhiActionPerformed(evt);
            }
        });

        jButtonThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-exit-icon.png"))); // NOI18N
        jButtonThoat.setText("ĐĂNG XUẤT");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("QUẢN LÝ ĐIỂM SINH VIÊN");

        jButtonTaoTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reseller-account-icon.png"))); // NOI18N
        jButtonTaoTaiKhoan.setText(" TÀI KHOẢN");
        jButtonTaoTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaoTaiKhoanActionPerformed(evt);
            }
        });

        jButtonDSSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Apps-preferences-contact-list-icon.png"))); // NOI18N
        jButtonDSSV.setText("IN DANH SÁCH SINH VIÊN");
        jButtonDSSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDSSVActionPerformed(evt);
            }
        });

        jButtonDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Apps-ksudoku-icon.png"))); // NOI18N
        jButtonDT.setText("IN ĐIỂM THI");
        jButtonDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDTActionPerformed(evt);
            }
        });

        jButtonBDMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Book-icon.png"))); // NOI18N
        jButtonBDMH.setText("IN BẢNG ĐIỂM MÔN HỌC");
        jButtonBDMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBDMHActionPerformed(evt);
            }
        });

        jButtonDSHP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dollar-folder-icon.png"))); // NOI18N
        jButtonDSHP.setText("IN DANH SÁCH HỌC PHÍ");
        jButtonDSHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDSHPActionPerformed(evt);
            }
        });

        jLabel2.setText("HỆ THỐNG");

        jLabel3.setText("QUẢN LÝ");

        jLabel4.setText("IN ẤN");

        jLabel5.setText("TÁC VỤ");

        jButtonBDTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dollar-folder-icon.png"))); // NOI18N
        jButtonBDTK.setText("IN BẢNG ĐIỂM TỔNG KẾT");
        jButtonBDTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBDTKActionPerformed(evt);
            }
        });

        jButtonPDSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Apps-ksudoku-icon.png"))); // NOI18N
        jButtonPDSV.setText("IN PHIẾU ĐIỂM SINH VIÊN");
        jButtonPDSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPDSVActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(177, 177, 177))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDSSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPDSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonDSHP, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(jButtonBDMH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonDT, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(jButtonBDTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(409, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(325, 325, 325))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(428, 428, 428))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(416, 416, 416))))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonTaoTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButtonThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonHocPhi)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonNhapDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonLop, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(176, 176, 176))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHocPhi)
                            .addComponent(jButtonNhapDiem)
                            .addComponent(jButtonThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTaoTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLop)
                    .addComponent(jButtonMonHoc)
                    .addComponent(jButtonSinhVien))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDT)
                    .addComponent(jButtonDSSV)
                    .addComponent(jButtonBDMH, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonDSHP)
                        .addComponent(jButtonBDTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jButtonPDSV, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        // TODO add your handling code here:
        DangNhapGUI dangNhapGUI = new DangNhapGUI();
        dangNhapGUI.setVisible(true);
        Program.changeSite = "";
        this.dispose();
    }//GEN-LAST:event_jButtonThoatActionPerformed

    private void jButtonLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLopActionPerformed
        // TODO add your handling code here:
        LopGUI lop = new LopGUI(this, true);
        lop.setVisible(true);
    }//GEN-LAST:event_jButtonLopActionPerformed

    private void jButtonSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinhVienActionPerformed
        try {
            // TODO add your handling code here:
            SinhVienGUI sinhVienGUI = new SinhVienGUI(this, true);
            sinhVienGUI.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSinhVienActionPerformed

    private void jButtonMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMonHocActionPerformed
        // TODO add your handling code here:
        MonHocGUI monHocGUI = new MonHocGUI(this, true);
        monHocGUI.setVisible(true);
    }//GEN-LAST:event_jButtonMonHocActionPerformed

    private void jButtonNhapDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNhapDiemActionPerformed
        // TODO add your handling code here:
        DiemGUI diemGUI = new DiemGUI(this, true);
        diemGUI.setVisible(true);
    }//GEN-LAST:event_jButtonNhapDiemActionPerformed

    private void jButtonHocPhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHocPhiActionPerformed
        // TODO add your handling code here:
        HocPhiGUI hocPhiGUI = new HocPhiGUI(this, true);
        hocPhiGUI.setVisible(true);
    }//GEN-LAST:event_jButtonHocPhiActionPerformed

    private void jButtonDSSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDSSVActionPerformed
        // TODO add your handling code here:
        INDanhSachSinhVienGUI danhSachSinhVienGUI = new INDanhSachSinhVienGUI(this, true);
        danhSachSinhVienGUI.setVisible(true);
    }//GEN-LAST:event_jButtonDSSVActionPerformed

    private void jButtonDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDTActionPerformed
        // TODO add your handling code here:
        InPhieuDiemThiGUI diemThiGUI = new InPhieuDiemThiGUI(this, true);
        diemThiGUI.setVisible(true);
    }//GEN-LAST:event_jButtonDTActionPerformed

    private void jButtonBDMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBDMHActionPerformed
        // TODO add your handling code here:
        InBangDiemMonHocGUI bangDiemMonHocGUI = new InBangDiemMonHocGUI(this, true);
        bangDiemMonHocGUI.setVisible(true);

    }//GEN-LAST:event_jButtonBDMHActionPerformed

    private void jButtonDSHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDSHPActionPerformed
        // TODO add your handling code here:
        InDanhSachDongHocPhiCuaLopGUI cuaLopGUI = new InDanhSachDongHocPhiCuaLopGUI(this, true);
        cuaLopGUI.setVisible(true);
    }//GEN-LAST:event_jButtonDSHPActionPerformed

    private void jButtonTaoTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaoTaiKhoanActionPerformed
        // TODO add your handling code here:
        TaoXoaLoginUPDATE taoXoaLoginUPDATE = new TaoXoaLoginUPDATE(this, true);
        taoXoaLoginUPDATE.setVisible(true);

    }//GEN-LAST:event_jButtonTaoTaiKhoanActionPerformed

    private void jButtonPDSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPDSVActionPerformed
        // TODO add your handling code here:
        InPhieuDiemSinhVienGUI diemSinhVienGUI = new InPhieuDiemSinhVienGUI(this, true);
        diemSinhVienGUI.setVisible(true);
    }//GEN-LAST:event_jButtonPDSVActionPerformed

    private void jButtonBDTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBDTKActionPerformed
        // TODO add your handling code here:
        InBangDiemTongKetGUI bangDiemTongKetGUI = new InBangDiemTongKetGUI(this, true);
        bangDiemTongKetGUI.setVisible(true);
    }//GEN-LAST:event_jButtonBDTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QuanLyGUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLyGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBDMH;
    private javax.swing.JButton jButtonBDTK;
    private javax.swing.JButton jButtonDSHP;
    private javax.swing.JButton jButtonDSSV;
    private javax.swing.JButton jButtonDT;
    private javax.swing.JButton jButtonHocPhi;
    private javax.swing.JButton jButtonLop;
    private javax.swing.JButton jButtonMonHoc;
    private javax.swing.JButton jButtonNhapDiem;
    private javax.swing.JButton jButtonPDSV;
    private javax.swing.JButton jButtonSinhVien;
    private javax.swing.JButton jButtonTaoTaiKhoan;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
