/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.LopDAO;
import DAO.SinhVienDAO;
import core.Lop;
import core.SinhVien;
import java.awt.Color;
import java.awt.Font;
import java.util.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pro
 */
public class SinhVienUPDATE extends javax.swing.JDialog {

    /**
     * Creates new form AddSinhVienDialog
     */
    private SinhVienDAO sinhvienDAO;
    private SinhVienGUI sinhvienGUI;
    private LopDAO lopDAO;
    private SinhVien previousStudent = null;
    private boolean updateMode = false;
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    SinhVien SVStack = new SinhVien();

    public SinhVienUPDATE(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        setColor();
        lopDAO = new LopDAO();
        lopDAO.loadComboboxLop(jComboBoxMaLop);
        this.jRadioButtonNam.setSelected(true);
        this.jRadioButtonKhong.setSelected(true);

        if (SinhVienGUI.status.equals("Them")) {

            this.jLabelTieuDe.setText("THÊM SINH VIÊN");
            this.jLabelNghiHoc.setEnabled(false);
            this.jRadioButtonKhong.setEnabled(false);
            this.jRadioButtonCo.setEnabled(false);

            this.jComboBoxMaLop.setSelectedItem(sinhvienGUI.MaLop);
            this.jComboBoxMaLop.setEnabled(false);

            //this.jLabelMaLop.setEnabled(false);
        } else if (SinhVienGUI.status.equals("CapNhat")) {

            this.jLabelTieuDe.setText("CẬP NHẬT SINH VIÊN");
            this.txtMASV.setEditable(false);

        }
        this.jLabelTieuDe.setFont(new Font("Calibri", Font.BOLD, 15));
        this.jLabelTieuDe.setSize(200, 20);
        this.jLabelTieuDe.setLocation(50, 50);

    }

    public SinhVienUPDATE(SinhVienGUI studentGUI, SinhVienDAO studentDAO) throws SQLException {
        this(studentGUI, studentDAO, null, false);
    }

    public SinhVienUPDATE(SinhVienGUI sinhvienGUI, SinhVienDAO sinhvienDAO, SinhVien thePreviousStudent, boolean theUpdateMode) throws SQLException {
        this(new javax.swing.JFrame(), true);
        this.sinhvienGUI = sinhvienGUI;
        this.sinhvienDAO = sinhvienDAO;
        this.previousStudent = thePreviousStudent;
        this.updateMode = theUpdateMode;
        if (updateMode) {

            populateGUI(previousStudent);
        }
    }

    private void populateGUI(SinhVien sv) {
        txtMASV.setText(sv.getMASV());
        txtHo.setText(sv.getHO());
        txtTen.setText(sv.getTEN());
        jComboBoxMaLop.setSelectedItem(sv.getMALOP());
        if (sv.isPHAI() == true) {
            jRadioButtonNam.setSelected(true);
        } else {
            jRadioButtonNu.setSelected(true);
        }

        txtNgaySinh.setText(sv.getDobString());
        txtNoiSinh.setText(sv.getNOISINH());
        txtDiaChi.setText(sv.getDIACHI());
        jTextAreaGhichu.setText(sv.getGHICHU());
        if (sv.isNGHIHOC() == true) {
            jRadioButtonCo.setSelected(true);
        } else {
            jRadioButtonKhong.setSelected(true);
        }
        SVStack = sv;
    }

    public void setColor() {
        this.getContentPane().setBackground(Color.orange);
        this.btnThem.setBackground(Color.GREEN);
        this.btnThoat.setBackground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lblMASV = new javax.swing.JLabel();
        txtMASV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabelMaLop = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNoiSinh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jRadioButtonNam = new javax.swing.JRadioButton();
        jRadioButtonNu = new javax.swing.JRadioButton();
        jLabelTieuDe = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelNghiHoc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaGhichu = new javax.swing.JTextArea();
        jRadioButtonCo = new javax.swing.JRadioButton();
        jRadioButtonKhong = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jComboBoxMaLop = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblMASV.setText("MASV:");

        txtMASV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMASVKeyPressed(evt);
            }
        });

        jLabel2.setText("Họ:");

        txtHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên:");

        jLabelMaLop.setText("Mã Lớp:");

        jLabel5.setText("Phái:");

        jLabel6.setText("Ngày Sinh:");

        txtNgaySinh.setText("22-08-1997");
        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });
        txtNgaySinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNgaySinhKeyPressed(evt);
            }
        });

        jLabel7.setText("Nơi Sinh:");

        jLabel8.setText("Địa Chỉ:");

        buttonGroup1.add(jRadioButtonNam);
        jRadioButtonNam.setText("Nam");

        buttonGroup1.add(jRadioButtonNu);
        jRadioButtonNu.setText("Nữ");

        jLabelTieuDe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel9.setText("Ghi Chú:");

        jLabelNghiHoc.setText("Nghỉ Học:");

        jTextAreaGhichu.setColumns(20);
        jTextAreaGhichu.setRows(5);
        jScrollPane1.setViewportView(jTextAreaGhichu);

        buttonGroup2.add(jRadioButtonCo);
        jRadioButtonCo.setText("Có");

        buttonGroup2.add(jRadioButtonKhong);
        jRadioButtonKhong.setText("Không");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Save-icon.png"))); // NOI18N
        btnThem.setText("Lưu");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-exit-icon.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jComboBoxMaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMaLopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addComponent(jLabelNghiHoc))
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jRadioButtonCo)
                                .addGap(96, 96, 96)
                                .addComponent(jRadioButtonKhong))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(203, 203, 203)
                                        .addComponent(jRadioButtonNu))
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNoiSinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(btnThem)
                                .addGap(56, 56, 56)
                                .addComponent(btnThoat))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(52, 52, 52)
                        .addComponent(jRadioButtonNam))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMASV)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabelMaLop))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTen, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(txtHo)
                            .addComponent(txtMASV)
                            .addComponent(jComboBoxMaLop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblMASV))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelTieuDe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMASV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaLop)
                    .addComponent(jComboBoxMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButtonNam)
                    .addComponent(jRadioButtonNu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNoiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNghiHoc)
                            .addComponent(jRadioButtonCo)
                            .addComponent(jRadioButtonKhong))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoat)
                    .addComponent(btnThem)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoActionPerformed

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (txtMASV.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "vui lòng nhập mã sinh viên");
        } else if (txtHo.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "vui lòng nhập họ");
        } else if (txtTen.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "vui lòng nhập tên");
        } else {
            saveSinhVien();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void jComboBoxMaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMaLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMaLopActionPerformed

    private void txtMASVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMASVKeyPressed
        // TODO add your handling code here:
        txtMASV.setEditable(false);
        if ((evt.getKeyChar() >= 48 && evt.getKeyChar() <= 57) || (evt.getKeyChar() >= 65 && evt.getKeyChar() <= 122) || evt.getKeyChar() == 8) {
            txtMASV.setEditable(true);
        }
    }//GEN-LAST:event_txtMASVKeyPressed

    private void txtNgaySinhKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNgaySinhKeyPressed
        // TODO add your handling code here:
        txtNgaySinh.setEditable(false);
        if ((evt.getKeyChar() >= 48 && evt.getKeyChar() <= 57) || evt.getKeyChar() == 45 || evt.getKeyChar() == 8) {
            txtNgaySinh.setEditable(true);
        }
    }//GEN-LAST:event_txtNgaySinhKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienUPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienUPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienUPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienUPDATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    SinhVienUPDATE dialog = new SinhVienUPDATE(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(SinhVienUPDATE.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    protected void saveSinhVien() {

        try {

            // get the student info from gui
            String MASV = txtMASV.getText();
            String Ho = txtHo.getText();
            String Ten = txtTen.getText();
            String MaLop = (String) jComboBoxMaLop.getSelectedItem();
            boolean Phai = isPhai();
            String NgaySinhString = txtNgaySinh.getText();
            Date NgaySinh = (Date) sdf.parse(NgaySinhString);
            String NoiSinh = txtNoiSinh.getText();
            String DiaChi = txtDiaChi.getText();
            String GhiChu = jTextAreaGhichu.getText();
            boolean NghiHoc = isNghiHoc();

            SinhVien tempSinhVien = null;

            if (!updateMode) {
                tempSinhVien = new SinhVien(MASV, Ho, Ten, MaLop, Phai, NgaySinh, NoiSinh, DiaChi, GhiChu, NghiHoc);
            } else {
                tempSinhVien = new SinhVien(previousStudent.getMASV(), Ho, Ten, MaLop, Phai, NgaySinh, NoiSinh, DiaChi, GhiChu, NghiHoc);
            }
            try {
                // save to the database
                if (updateMode) {
                    sinhvienDAO.capNhatSinhVienPROC(tempSinhVien);
                    sinhvienGUI.stringSV.push("CapNhat");
                    sinhvienGUI.stackSV.push(SVStack);
                } else {
                    sinhvienDAO.themSinhVienPROC(tempSinhVien);
                    sinhvienGUI.stringSV.push("Them");
                    sinhvienGUI.stackSV.push(tempSinhVien);
                }
                // close dialog
                setVisible(false);
                dispose();
                // refresh gui list
                sinhvienGUI.displaySinhVien();

                // show success message
                if (!updateMode) {
                    JOptionPane.showMessageDialog(sinhvienGUI,
                            "Thêm sinh viên thành công",
                            "",
                            JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(sinhvienGUI,
                            "Cập nhật sinh viên thành công.",
                            "",
                            JOptionPane.INFORMATION_MESSAGE);

                }
            } catch (Exception exc) {
                JOptionPane.showMessageDialog(
                        sinhvienGUI,
                        "Lỗi lưu sinh viên: "
                        + exc.getMessage(), "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng ngày");
        }
    }

    public boolean isPhai() {
        if (jRadioButtonNam.isSelected()) {
            return true;
        } else {
            return false;
        }

    }

    public boolean isNghiHoc() {
        if (jRadioButtonCo.isSelected()) {
            return true;
        } else {
            return false;
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> jComboBoxMaLop;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMaLop;
    private javax.swing.JLabel jLabelNghiHoc;
    private javax.swing.JLabel jLabelTieuDe;
    private javax.swing.JRadioButton jRadioButtonCo;
    private javax.swing.JRadioButton jRadioButtonKhong;
    private javax.swing.JRadioButton jRadioButtonNam;
    private javax.swing.JRadioButton jRadioButtonNu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaGhichu;
    private javax.swing.JLabel lblMASV;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtMASV;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtNoiSinh;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
